device_type: "Tracker" # Tracker, Anchor
is_initiator: False
priority: 0
label: 0x0000
network_id: 0x0000
update_time_ms: 100
is_auto_anchor_positioning: False
anchor_height: 0
is_tracker_stream_mode: True
tracker_message_mode: "Long" # Long, Short
is_led_enabled: True
x: 0
y: 0
z: 0
